# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-04 23:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0002_auto_20160604_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Califica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_Calificacion', models.IntegerField(blank=True, max_length=1, null=True)),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='califica', to='movies.Pelicula')),
            ],
        ),
        migrations.CreateModel(
            name='Coleccion',
            fields=[
                ('genero', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Contiene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cont2', to='movies.Pelicula')),
            ],
        ),
        migrations.CreateModel(
            name='ContieneColeccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cont2_2', to='movies.Pelicula')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cont2_1', to='users.Contiene')),
            ],
        ),
        migrations.CreateModel(
            name='Generos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Genero', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lista_peliculas_porver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista1_2', to='movies.Pelicula')),
            ],
        ),
        migrations.CreateModel(
            name='Lista_peliculas_vistas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime(2016, 6, 4, 23, 2, 9, 790374))),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista2_1', to='movies.Pelicula')),
            ],
        ),
        migrations.CreateModel(
            name='Lista_personal',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('contrasena', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Auditor',
            fields=[
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='auditor', serialize=False, to='users.Usuario')),
                ('documento_id', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorias_favoritas',
            fields=[
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cat1', serialize=False, to='users.Usuario')),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cliente1', serialize=False, to='users.Usuario')),
                ('contrasena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Usuario')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente2', to='users.Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='contiene',
            name='nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cont1', to='users.Lista_personal'),
        ),
        migrations.AddField(
            model_name='lista_personal',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista3_1', to='users.Cliente'),
        ),
        migrations.AddField(
            model_name='lista_peliculas_vistas',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista2_1', to='users.Cliente'),
        ),
        migrations.AddField(
            model_name='lista_peliculas_porver',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista1_1', to='users.Cliente'),
        ),
        migrations.AddField(
            model_name='generos',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genero2', to='users.Cliente'),
        ),
        migrations.AddField(
            model_name='contienecoleccion',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cont2_3', to='users.Cliente'),
        ),
        migrations.AddField(
            model_name='contiene',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cont3', to='users.Cliente'),
        ),
        migrations.AddField(
            model_name='coleccion',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista4_1', to='users.Cliente'),
        ),
        migrations.AddField(
            model_name='califica',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='califica', to='users.Cliente'),
        ),
        migrations.AddField(
            model_name='auditor',
            name='contrasena',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditor3', to='users.Usuario'),
        ),
        migrations.AddField(
            model_name='auditor',
            name='nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditor2', to='users.Usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='lista_peliculas_vistas',
            unique_together=set([('email', 'codigo')]),
        ),
        migrations.AlterUniqueTogether(
            name='lista_peliculas_porver',
            unique_together=set([('email', 'codigo')]),
        ),
        migrations.AlterUniqueTogether(
            name='generos',
            unique_together=set([('id', 'email')]),
        ),
        migrations.AlterUniqueTogether(
            name='contienecoleccion',
            unique_together=set([('genero', 'codigo', 'email')]),
        ),
        migrations.AlterUniqueTogether(
            name='contiene',
            unique_together=set([('nombre', 'codigo', 'email')]),
        ),
        migrations.AlterUniqueTogether(
            name='califica',
            unique_together=set([('codigo', 'email')]),
        ),
    ]
