# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-04 23:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditor',
            name='contrasena',
        ),
        migrations.RemoveField(
            model_name='auditor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='auditor',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='contrasena',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nombre',
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='califica',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='califica', to='users.Usuario'),
        ),
        migrations.AlterField(
            model_name='coleccion',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista4_1', to='users.Usuario'),
        ),
        migrations.AlterField(
            model_name='contiene',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cont3', to='users.Usuario'),
        ),
        migrations.AlterField(
            model_name='contienecoleccion',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cont2_3', to='users.Usuario'),
        ),
        migrations.AlterField(
            model_name='generos',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genero2', to='users.Usuario'),
        ),
        migrations.AlterField(
            model_name='lista_peliculas_porver',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista1_1', to='users.Usuario'),
        ),
        migrations.AlterField(
            model_name='lista_peliculas_vistas',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista2_1', to='users.Usuario'),
        ),
        migrations.AlterField(
            model_name='lista_peliculas_vistas',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2016, 6, 4, 23, 6, 50, 241748)),
        ),
        migrations.AlterField(
            model_name='lista_personal',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista3_1', to='users.Usuario'),
        ),
        migrations.DeleteModel(
            name='Auditor',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
