# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-05 06:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160604_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorias_favoritas',
            name='email',
        ),
        migrations.AlterField(
            model_name='lista_peliculas_vistas',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2016, 6, 5, 6, 44, 7, 399858)),
        ),
        migrations.AlterUniqueTogether(
            name='generos',
            unique_together=set([('id_Genero', 'email')]),
        ),
        migrations.DeleteModel(
            name='Categorias_favoritas',
        ),
    ]
