# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-07 16:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_genero'),
        ('users', '0004_auto_20160607_0146'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='generos',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='generos',
            name='email',
        ),
        migrations.AddField(
            model_name='usuario',
            name='generos',
            field=models.ManyToManyField(to='movies.Genero'),
        ),
        migrations.AlterField(
            model_name='lista_peliculas_vistas',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2016, 6, 7, 16, 5, 41, 815946)),
        ),
        migrations.DeleteModel(
            name='Generos',
        ),
    ]
