# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-08 04:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_genero'),
        ('users', '0012_auto_20160608_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='generos',
            field=models.ManyToManyField(to='movies.Genero'),
        ),
        migrations.AlterField(
            model_name='lista_peliculas_vistas',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2016, 6, 8, 4, 2, 55, 129242)),
        ),
    ]
