# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-08 04:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20160608_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista_peliculas_vistas',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2016, 6, 8, 4, 3, 0, 748375)),
        ),
    ]
