# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-09 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_genero'),
        ('users', '0016_auto_20160608_0455'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lista_peliculas_porver',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='lista_peliculas_porver',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='lista_peliculas_porver',
            name='email',
        ),
        migrations.AlterUniqueTogether(
            name='lista_peliculas_vistas',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='lista_peliculas_vistas',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='lista_peliculas_vistas',
            name='email',
        ),
        migrations.AddField(
            model_name='usuario',
            name='lista_peliculas_porver',
            field=models.ManyToManyField(related_name='lista_porver', to='movies.Pelicula'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='lista_peliculas_vistas',
            field=models.ManyToManyField(related_name='lista_vistas', to='movies.Pelicula'),
        ),
        migrations.DeleteModel(
            name='Lista_peliculas_porver',
        ),
        migrations.DeleteModel(
            name='Lista_peliculas_vistas',
        ),
    ]
