# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-09 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_genero'),
        ('users', '0017_auto_20160609_0222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coleccion',
            old_name='genero',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='coleccion',
            name='contenido',
            field=models.ManyToManyField(default='', related_name='coleccion3', to='movies.Pelicula'),
        ),
        migrations.AddField(
            model_name='lista_personal',
            name='contenido',
            field=models.ManyToManyField(related_name='lista_personal', to='movies.Pelicula'),
        ),
        migrations.AlterUniqueTogether(
            name='lista_personal',
            unique_together=set([('nombre', 'email')]),
        ),
    ]
