# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-09 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_genero'),
        ('users', '0019_auto_20160609_0316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coleccion2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.ManyToManyField(to='movies.Pelicula')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista4_1', to='users.Usuario')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='li', to='movies.Genero')),
            ],
        ),
        migrations.CreateModel(
            name='Lista_personal2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('contenido', models.ManyToManyField(to='movies.Pelicula')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista3_1', to='users.Usuario')),
            ],
        ),
        migrations.RemoveField(
            model_name='coleccion',
            name='contenido',
        ),
        migrations.RemoveField(
            model_name='coleccion',
            name='email',
        ),
        migrations.AlterUniqueTogether(
            name='lista_personal',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='lista_personal',
            name='contenido',
        ),
        migrations.RemoveField(
            model_name='lista_personal',
            name='email',
        ),
        migrations.DeleteModel(
            name='Coleccion',
        ),
        migrations.DeleteModel(
            name='Lista_personal',
        ),
        migrations.AlterUniqueTogether(
            name='lista_personal2',
            unique_together=set([('nombre', 'email')]),
        ),
        migrations.AlterUniqueTogether(
            name='coleccion2',
            unique_together=set([('nombre', 'email')]),
        ),
    ]
