# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-09 04:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20160609_0403'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coleccion2',
            new_name='Coleccion',
        ),
        migrations.RenameModel(
            old_name='Lista_personal2',
            new_name='Lista_personal',
        ),
    ]
