# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-09 05:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20160609_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coleccion',
            name='nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='li', to='movies.Generos'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='generos',
            field=models.ManyToManyField(to='movies.Generos'),
        ),
    ]
