# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-09 06:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20160609_0552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coleccion',
            old_name='nombre',
            new_name='id_genero',
        ),
        migrations.AlterUniqueTogether(
            name='coleccion',
            unique_together=set([('id_genero', 'email')]),
        ),
    ]
