# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-12 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20160609_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='genero',
            name='nombre',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
