# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-24 04:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0024_auto_20160612_0838'),
        ('users', '0028_auto_20160612_0335'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechaPeliculaVista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fecha', to='movies.Pelicula')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fecha', to='users.Usuario')),
            ],
            options={
                'verbose_name': 'FechaPeliculaVista',
                'verbose_name_plural': 'FechasPeliculasVistas',
            },
        ),
        migrations.AlterUniqueTogether(
            name='fechapeliculavista',
            unique_together=set([('codigo', 'email')]),
        ),
    ]
