# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-30 01:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20160624_0414'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coleccion',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='coleccion',
            name='contenido',
        ),
        migrations.RemoveField(
            model_name='coleccion',
            name='email',
        ),
        migrations.RemoveField(
            model_name='coleccion',
            name='id_genero',
        ),
        migrations.DeleteModel(
            name='Coleccion',
        ),
    ]
