# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-30 01:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0024_auto_20160612_0838'),
        ('users', '0030_auto_20160630_0141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coleccion',
            fields=[
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='lista4_1', serialize=False, to='users.Usuario')),
                ('contenido', models.ManyToManyField(to='movies.Pelicula')),
            ],
            options={
                'verbose_name': 'Coleccion',
                'verbose_name_plural': 'Colecciones',
            },
        ),
    ]
