# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-29 03:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Califica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_Calificacion', models.IntegerField(blank=True, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contiene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Critica_calificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Critica_calificacion', models.CharField(blank=True, max_length=700, null=True)),
                ('critico', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lista_peliculas_porver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Lista_peliculas_vistas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Lista_personal',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen', models.CharField(blank=True, max_length=500, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('an_o', models.CharField(blank=True, max_length=100, null=True)),
                ('trailer', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_estreno', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('contrasena', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Auditor',
            fields=[
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='auditor', serialize=False, to='movies.Usuario')),
                ('documento_id', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorias_favoritas',
            fields=[
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cat1', serialize=False, to='movies.Usuario')),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cliente1', serialize=False, to='movies.Usuario')),
                ('contrasena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Usuario')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente2', to='movies.Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='lista_peliculas_vistas',
            name='codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista2_1', to='movies.Pelicula'),
        ),
        migrations.AddField(
            model_name='lista_peliculas_porver',
            name='codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista1_2', to='movies.Pelicula'),
        ),
        migrations.AddField(
            model_name='critica_calificacion',
            name='codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Pelicula'),
        ),
        migrations.AddField(
            model_name='contiene',
            name='codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cont2', to='movies.Pelicula'),
        ),
        migrations.AddField(
            model_name='contiene',
            name='nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cont1', to='movies.Lista_personal'),
        ),
        migrations.AddField(
            model_name='califica',
            name='codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='califica', to='movies.Pelicula'),
        ),
        migrations.AddField(
            model_name='actores',
            name='codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Pelicula'),
        ),
        migrations.AddField(
            model_name='lista_personal',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista3_1', to='movies.Cliente'),
        ),
        migrations.AddField(
            model_name='lista_peliculas_vistas',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista2_1', to='movies.Cliente'),
        ),
        migrations.AddField(
            model_name='lista_peliculas_porver',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista1_1', to='movies.Cliente'),
        ),
        migrations.AlterUniqueTogether(
            name='contiene',
            unique_together=set([('nombre', 'codigo')]),
        ),
        migrations.AddField(
            model_name='califica',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='califica', to='movies.Cliente'),
        ),
        migrations.AddField(
            model_name='auditor',
            name='contrasena',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditor3', to='movies.Usuario'),
        ),
        migrations.AddField(
            model_name='auditor',
            name='nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditor2', to='movies.Usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='actores',
            unique_together=set([('codigo', 'actor')]),
        ),
        migrations.AlterUniqueTogether(
            name='lista_peliculas_vistas',
            unique_together=set([('email', 'codigo')]),
        ),
        migrations.AlterUniqueTogether(
            name='lista_peliculas_porver',
            unique_together=set([('email', 'codigo')]),
        ),
        migrations.AlterUniqueTogether(
            name='califica',
            unique_together=set([('codigo', 'email')]),
        ),
    ]
