# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-09 04:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_genero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='critica_calificacion',
            options={'verbose_name': 'Critica_calificacion', 'verbose_name_plural': 'Criticas_calificaciones'},
        ),
    ]
