# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-09 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20160609_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
