# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-09 06:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20160609_0558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genero',
            old_name='id',
            new_name='id_genero',
        ),
    ]
