# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-09 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20160609_0603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genero',
            old_name='nombre',
            new_name='name',
        ),
    ]
