# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-09 06:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20160609_0615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genero',
            name='name',
        ),
    ]
