# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-09 06:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20160609_0620'),
        ('movies', '0011_remove_genero_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genero',
        ),
    ]
