# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-11 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_genero_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genero',
            old_name='id',
            new_name='id_genero',
        ),
        migrations.RemoveField(
            model_name='genero',
            name='nombre',
        ),
    ]
