# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-12 01:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_genero_nombre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genero',
        ),
    ]
