# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-12 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0020_auto_20160612_0327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=70)),
            ],
        ),
        migrations.AddField(
            model_name='pelicula',
            name='criticas',
            field=models.ManyToManyField(to='movies.Critica_calificacion'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='descripcion',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='fechaEstreno',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='imagen',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='trailer',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.RemoveField(
            model_name='critica_calificacion',
            name='codigo',
        ),
        migrations.AlterUniqueTogether(
            name='critica_calificacion',
            unique_together=set([('critico', 'critica_calificacion')]),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='generos',
            field=models.ManyToManyField(to='movies.Genero'),
        ),
    ]
