# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-12 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0022_auto_20160612_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='codigo',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='fechaEstreno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
