# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-12 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0023_auto_20160612_0442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('nombre', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='pelicula',
            name='actores',
            field=models.ManyToManyField(to='movies.Actor'),
        ),
    ]
